MF      = Makefile.libsci

SRC	= dgemv_benchmark.f90


FC      = ftn
PP      = 

LDFLAGS =   -L${MKLROOT}/lib/intel64 -Wl,--no-as-needed -lmkl_gf_lp64 -lmkl_sequential -lmkl_core -lpthread -lm -ldl
FFLAGS  =  -O3 $(PP)
LIBS    = 

EXE	= dgemv_mkl.x

.SUFFIXES: .f90 .o

OBJ	=$(SRC:.f90=.o)

.f90.o:
	$(FC) -c $(FFLAGS) $<

all:	$(EXE)

$(EXE):$(OBJ)
	$(FC) $(LDFLAGS) -o $@ $(OBJ) $(LIBS)

$(OBJ): $(MF)

clean:
	rm -fr $(TMP) $(OBJ) $(EXE) core


